name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task0:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: lint
        run: |
          cd module3_task1/
          make lint
      - name: Setup Hugo
        run: |
          cd module3_task1/
          sudo ./setup.sh
      - name: build
        run: |
          cd module3_task1/
          make build
      - name: post
        run: |
          cd module3_task1/
          make POST_TITLE="Test Title" POST_NAME="Test-name" post
      - name: tests
        run: |
          cd module3_task1/
          make package
          make clean
      - name: archive build
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task2/awesome-website.zip
